var annotated_dup =
[
    [ "Runevision", "namespaceRunevision.html", [
      [ "Common", "namespaceRunevision_1_1Common.html", [
        [ "Array2DPool", "classRunevision_1_1Common_1_1Array2DPool.html", "classRunevision_1_1Common_1_1Array2DPool" ],
        [ "Array3DPool", "classRunevision_1_1Common_1_1Array3DPool.html", "classRunevision_1_1Common_1_1Array3DPool" ],
        [ "ArrayPool", "classRunevision_1_1Common_1_1ArrayPool.html", "classRunevision_1_1Common_1_1ArrayPool" ],
        [ "CollectionExtensions", "classRunevision_1_1Common_1_1CollectionExtensions.html", null ],
        [ "Crd", "classRunevision_1_1Common_1_1Crd.html", null ],
        [ "DebugButton", "classRunevision_1_1Common_1_1DebugButton.html", null ],
        [ "DebugDrawer", "classRunevision_1_1Common_1_1DebugDrawer.html", null ],
        [ "DebugFoldout", "classRunevision_1_1Common_1_1DebugFoldout.html", null ],
        [ "DebugOption", "classRunevision_1_1Common_1_1DebugOption.html", null ],
        [ "DebugOptions", "classRunevision_1_1Common_1_1DebugOptions.html", null ],
        [ "DebugRadioButton", "classRunevision_1_1Common_1_1DebugRadioButton.html", null ],
        [ "DebugToggle", "classRunevision_1_1Common_1_1DebugToggle.html", null ],
        [ "DFloat", "structRunevision_1_1Common_1_1DFloat.html", null ],
        [ "DPoint", "structRunevision_1_1Common_1_1DPoint.html", null ],
        [ "DPoint3", "structRunevision_1_1Common_1_1DPoint3.html", null ],
        [ "ForwardingUnityWrapper", "classRunevision_1_1Common_1_1ForwardingUnityWrapper.html", null ],
        [ "GridBounds", "structRunevision_1_1Common_1_1GridBounds.html", null ],
        [ "GridBounds3", "structRunevision_1_1Common_1_1GridBounds3.html", null ],
        [ "IPool", "interfaceRunevision_1_1Common_1_1IPool.html", "interfaceRunevision_1_1Common_1_1IPool" ],
        [ "IPoolable", "interfaceRunevision_1_1Common_1_1IPoolable.html", "interfaceRunevision_1_1Common_1_1IPoolable" ],
        [ "ListPool", "classRunevision_1_1Common_1_1ListPool.html", "classRunevision_1_1Common_1_1ListPool" ],
        [ "Logg", "classRunevision_1_1Common_1_1Logg.html", null ],
        [ "ObjectPool", "classRunevision_1_1Common_1_1ObjectPool.html", "classRunevision_1_1Common_1_1ObjectPool" ],
        [ "Point", "structRunevision_1_1Common_1_1Point.html", null ],
        [ "Point3", "structRunevision_1_1Common_1_1Point3.html", null ],
        [ "PoolManager", "classRunevision_1_1Common_1_1PoolManager.html", null ],
        [ "RandomHash", "structRunevision_1_1Common_1_1RandomHash.html", null ],
        [ "RunevisionUnityExtensions", "classRunevision_1_1Common_1_1RunevisionUnityExtensions.html", null ],
        [ "SimpleProfiler", "classRunevision_1_1Common_1_1SimpleProfiler.html", "classRunevision_1_1Common_1_1SimpleProfiler" ],
        [ "TypeExtensions", "classRunevision_1_1Common_1_1TypeExtensions.html", null ]
      ] ],
      [ "LayerProcGen", "namespaceRunevision_1_1LayerProcGen.html", [
        [ "AbstractChunkBasedDataLayer", "classRunevision_1_1LayerProcGen_1_1AbstractChunkBasedDataLayer.html", "classRunevision_1_1LayerProcGen_1_1AbstractChunkBasedDataLayer" ],
        [ "AbstractDataLayer", "classRunevision_1_1LayerProcGen_1_1AbstractDataLayer.html", "classRunevision_1_1LayerProcGen_1_1AbstractDataLayer" ],
        [ "AbstractLayerChunk", "classRunevision_1_1LayerProcGen_1_1AbstractLayerChunk.html", "classRunevision_1_1LayerProcGen_1_1AbstractLayerChunk" ],
        [ "ChunkBasedDataLayer", "classRunevision_1_1LayerProcGen_1_1ChunkBasedDataLayer.html", "classRunevision_1_1LayerProcGen_1_1ChunkBasedDataLayer" ],
        [ "GenerationSource", "classRunevision_1_1LayerProcGen_1_1GenerationSource.html", null ],
        [ "IChunkBasedDataLayer", "interfaceRunevision_1_1LayerProcGen_1_1IChunkBasedDataLayer.html", "interfaceRunevision_1_1LayerProcGen_1_1IChunkBasedDataLayer" ],
        [ "ILayerVisualization", "interfaceRunevision_1_1LayerProcGen_1_1ILayerVisualization.html", null ],
        [ "ILC", "interfaceRunevision_1_1LayerProcGen_1_1ILC.html", null ],
        [ "IQueuedAction", "interfaceRunevision_1_1LayerProcGen_1_1IQueuedAction.html", "interfaceRunevision_1_1LayerProcGen_1_1IQueuedAction" ],
        [ "LayerChunk", "classRunevision_1_1LayerProcGen_1_1LayerChunk.html", "classRunevision_1_1LayerProcGen_1_1LayerChunk" ],
        [ "LayerDependency", "classRunevision_1_1LayerProcGen_1_1LayerDependency.html", null ],
        [ "LayerManager", "classRunevision_1_1LayerProcGen_1_1LayerManager.html", null ],
        [ "LayerManagerBehavior", "classRunevision_1_1LayerProcGen_1_1LayerManagerBehavior.html", null ],
        [ "LayerNamedReference", "classRunevision_1_1LayerProcGen_1_1LayerNamedReference.html", null ],
        [ "MainThreadActionQueue", "classRunevision_1_1LayerProcGen_1_1MainThreadActionQueue.html", "classRunevision_1_1LayerProcGen_1_1MainThreadActionQueue" ],
        [ "QueuedCallback", "structRunevision_1_1LayerProcGen_1_1QueuedCallback.html", "structRunevision_1_1LayerProcGen_1_1QueuedCallback" ],
        [ "QueuedGameObjectDestruction", "structRunevision_1_1LayerProcGen_1_1QueuedGameObjectDestruction.html", "structRunevision_1_1LayerProcGen_1_1QueuedGameObjectDestruction" ],
        [ "RollingGrid", "classRunevision_1_1LayerProcGen_1_1RollingGrid.html", null ],
        [ "TopLayerDependency", "classRunevision_1_1LayerProcGen_1_1TopLayerDependency.html", null ],
        [ "TransformWrapper", "classRunevision_1_1LayerProcGen_1_1TransformWrapper.html", "classRunevision_1_1LayerProcGen_1_1TransformWrapper" ],
        [ "VisualizationManager", "classRunevision_1_1LayerProcGen_1_1VisualizationManager.html", "classRunevision_1_1LayerProcGen_1_1VisualizationManager" ],
        [ "WorkTracker", "classRunevision_1_1LayerProcGen_1_1WorkTracker.html", null ]
      ] ],
      [ "SaveState", "namespaceRunevision_1_1SaveState.html", [
        [ "FBPPChooser", "classRunevision_1_1SaveState_1_1FBPPChooser.html", null ],
        [ "StateObject", "classRunevision_1_1SaveState_1_1StateObject.html", null ],
        [ "StateWrapper", "classRunevision_1_1SaveState_1_1StateWrapper.html", null ],
        [ "WorldState", "classRunevision_1_1SaveState_1_1WorldState.html", null ],
        [ "WorldStateBinary", "classRunevision_1_1SaveState_1_1WorldStateBinary.html", null ],
        [ "WorldStateFBPP", "classRunevision_1_1SaveState_1_1WorldStateFBPP.html", null ],
        [ "WorldStateLocal", "classRunevision_1_1SaveState_1_1WorldStateLocal.html", null ]
      ] ],
      [ "UnityEditor", "namespaceRunevision_1_1UnityEditor.html", [
        [ "DebugOptionsWindow", "classRunevision_1_1UnityEditor_1_1DebugOptionsWindow.html", null ],
        [ "GenerationSourceEditor", "classRunevision_1_1UnityEditor_1_1GenerationSourceEditor.html", null ],
        [ "GridBounds3Drawer", "classRunevision_1_1UnityEditor_1_1GridBounds3Drawer.html", null ],
        [ "GridBoundsDrawer", "classRunevision_1_1UnityEditor_1_1GridBoundsDrawer.html", null ],
        [ "LayerNamedReferenceDrawer", "classRunevision_1_1UnityEditor_1_1LayerNamedReferenceDrawer.html", null ],
        [ "LayerSpecDrawer", "classRunevision_1_1UnityEditor_1_1LayerSpecDrawer.html", null ],
        [ "Point3Drawer", "classRunevision_1_1UnityEditor_1_1Point3Drawer.html", null ],
        [ "PointDrawer", "classRunevision_1_1UnityEditor_1_1PointDrawer.html", null ]
      ] ]
    ] ],
    [ "CallbackHub", "classCallbackHub.html", null ]
];